# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-31 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/none/no-img.jpg', upload_to='images/'),
        ),
    ]
